### ISSUE TITLE
"Type should be a Symbol, not: [nil, nil] in {nil=>nil}" exception using Brakeman library

### ISSUE THREAD

**Issue by BartlomiejSkwira** [presidentbeef/brakeman#1037]
When I run Brakeman with a predefined rake task I get this exception:
```
rake aborted!
Type should be a Symbol, not: [nil, nil] in {nil=>nil}
/bundle/gems/brakeman-3.6.1/lib/ruby_parser/bm_sexp_processor.rb:69:in `process'
/bundle/gems/brakeman-3.6.1/lib/brakeman/processors/lib/find_all_calls.rb:22:in `process_source'
/bundle/gems/brakeman-3.6.1/lib/brakeman/tracker.rb:223:in `block in index_call_sites'
/bundle/gems/brakeman-3.6.1/lib/brakeman/tracker.rb:107:in `block in each_template'
/bundle/gems/brakeman-3.6.1/lib/brakeman/tracker.rb:106:in `each'
/bundle/gems/brakeman-3.6.1/lib/brakeman/tracker.rb:106:in `each_template'
/bundle/gems/brakeman-3.6.1/lib/brakeman/tracker.rb:222:in `index_call_sites'
/bundle/gems/brakeman-3.6.1/lib/brakeman/scanner.rb:312:in `index_call_sites'
/bundle/gems/brakeman-3.6.1/lib/brakeman/scanner.rb:63:in `process'
/bundle/gems/brakeman-3.6.1/lib/brakeman.rb:364:in `scan'
/bundle/gems/brakeman-3.6.1/lib/brakeman.rb:73:in `run'
/project_name/lib/tasks/brakeman.rake:17:in `block (2 levels) in <top (required)>'
...
Tasks: TOP => brakeman:run
```

My rake task definition:
```
namespace :brakeman do

  #example usage:
  #rake brakeman:run #will produce 'report.html'
  #rake brakeman:run[report.json]
  desc "Run Brakeman and create a report file"
  task :run, :output_files do |t, args|
    require 'brakeman'

    files = if args[:output_files]
      args[:output_files].split(' ')
    else
      ["report.html"]
    end

    Brakeman.run app_path:  ".", output_files: files, print_report: true
  end
end
```

I'm on version 3.6.1
When I run Brakeman from CLI with this `brakeman -q -3 -o report.html` there are no issues.

**Comment by presidentbeef** [comment]
It is very difficult to tell what causes this. However, I strongly recommend *not* using the Rake task, as using Rake with Rails loads the entire Rails environment (and dependencies) which can cause conflicts with Brakeman.

**Comment by BartlomiejSkwira** [comment]
Yeah, I used the CLI version. Maybe someone in the future will solve this one. Closed
