### ISSUE TITLE
Parse Error on ruby 2.5

### ISSUE THREAD

**Issue by marocchino** [presidentbeef/brakeman#1173]
### Background

Brakeman version: 4.2.1
Rails version: 5.1.5
Ruby version: 2.5.0p0

#### Parse Error

```
== Errors ==

Error: /Users/shim.taewon/Documents/Zodiac-backend/lib/excel_importer/model_transactable.rb:9 :: parse error on value ["rescue", 9] (kRESCUE)
Location: Could not parse /Users/shim.taewon/Documents/Zodiac-backend/lib/excel_importer/model_transactable.rb

$ ruby -c lib/excel_importer/model_transactable.rb
Syntax OK
```

Minimal example that does not parse:

```ruby
    def save_models
      models_with_index do |model, index|
        model.save!
      rescue StandardError => err
        error(model, index, err)
      end
    end
```

Maybe you need to update ruby parser.

**Comment by presidentbeef** [comment]
Hi @marocchino,

RubyParser does not support this syntax yet:

```
Successfully installed ruby_parser-3.11.0
1 gem installed
[justin@bigblue brakeman (master)]$ irb
2.5.0 :001 > require 'ruby_parser'
R => true 
2.5.0 :002 > RubyParser.new.parse <<-RUBY
2.5.0 :003">     def save_models
2.5.0 :004">       models_with_index do |model, index|
2.5.0 :005">         model.save!
2.5.0 :006">       rescue StandardError => err
2.5.0 :007">         error(model, index, err)
2.5.0 :008">       end
2.5.0 :009">     end
2.5.0 :010"> RUBY
Traceback (most recent call last):
       16: from /home/justin/.rvm/rubies/ruby-2.5.0/bin/irb:11:in `<main>'
       15: from (irb):2
       14: from /home/justin/.rvm/gems/ruby-2.5.0@test/gems/ruby_parser-3.11.0/lib/ruby_parser.rb:28:in `process'
       13: from /home/justin/.rvm/gems/ruby-2.5.0@test/gems/ruby_parser-3.11.0/lib/ruby_parser.rb:28:in `each'
       12: from /home/justin/.rvm/gems/ruby-2.5.0@test/gems/ruby_parser-3.11.0/lib/ruby_parser.rb:31:in `block in process'
       11: from /home/justin/.rvm/gems/ruby-2.5.0@test/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1070:in `process'
       10: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:108:in `timeout'
        9: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:33:in `catch'
        8: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:33:in `catch'
        7: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:33:in `block in catch'
        6: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/timeout.rb:93:in `block in timeout'
        5: from /home/justin/.rvm/gems/ruby-2.5.0@test/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1082:in `block in process'
        4: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/racc/parser.rb:259:in `do_parse'
        3: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/racc/parser.rb:259:in `_racc_do_parse_c'
        2: from /home/justin/.rvm/gems/ruby-2.5.0@test/gems/ruby_parser-3.11.0/lib/ruby_parser_extras.rb:1175:in `on_error'
        1: from /home/justin/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/racc/parser.rb:528:in `on_error'
Racc::ParseError ((string):4 :: parse error on value ["rescue", 4] (kRESCUE))
```

**Comment by marocchino** [comment]
@presidentbeef 😮  OK. 
I will make issue on ruby_parser.
Should I close this issue?

**Comment by marocchino** [comment]
https://github.com/seattlerb/ruby_parser/issues/262

**Comment by presidentbeef** [comment]
We can leave this open for now in case other people have the issue and to remind me to see if I can fix it in ruby_parser.

**Comment by tobypinder** [comment]
This is tripping us up as well, I think you're likely to see a number of cases as we encountered this issue following a refactor towards [rubocop](https://github.com/rubocop-hq/rubocop) conformance - it seems that rubocop pushes users to this particular style (at least in our configuration of it)

**Comment by presidentbeef** [comment]
Opened https://github.com/seattlerb/ruby_parser/pull/264

**Comment by craineum** [comment]
Is this just waiting on ruby_parser to cut a new version?

**Comment by presidentbeef** [comment]
Yes, essentially.

**Comment by djpate** [comment]
Seems like `ruby_parser` was released yesterday but it does not seem to fix the issue for me.

**Comment by benhutton** [comment]
same here. @presidentbeef does `brakeman` need an update to be compatible with the new `ruby_parser`?

**Comment by presidentbeef** [comment]
Since the `brakeman` gem bundles its dependencies and the `brakeman-lib` and `brakeman-min` gems are locked to older versions of RubyParser, a release is required. Unfortunately I'm waiting on some licensing issues to be resolved first. Hopefully we'll see a release by the end of the week.

In the meantime, if you are declaring the Brakeman dependency in a `Gemfile`, you can pull directly from git:

```ruby
gem "brakeman", git: "https://github.com/presidentbeef/brakeman.git", ref: "1bff87f51e5a33890a7f9e56e35196a20242b935"
```

**Comment by presidentbeef** [comment]
This is in the latest Brakeman release (4.4.0).
