### ISSUE TITLE
YAML with ERB parsing issue

### ISSUE THREAD

**Issue by jeffpereira** [presidentbeef/brakeman#1234]
### Background

Brakeman version: 4.2.0
Rails version: 2.4.3
Ruby version: 5.1

Link to Rails application code: https://gist.github.com/jeffpereira/b7478eee904cb9d717b364d6681e31ee

#### Parse Error

Minimal example that does not parse:

This is in secrets.yml.  We have dynamic environment names.

```
<%= FOO.env.rails %>:
  <<: *<%= FOO.env %>
```

#### Other Error

Stack trace:

```
Processing found calls(<unknown>): did not find expected alphabetic or numeric character while scanning an alias at line 140 column 7
/Users/jpereira/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/brakeman-3.6.1/bundle/ruby/2.3.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `parse'
/Users/jpereira/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/brakeman-3.6.1/bundle/ruby/2.3.0/gems/safe_yaml-1.0.4/lib/safe_yaml/load.rb:143:in `load'

/Users/jpereira/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/brakeman-3.6.1/lib/brakeman/checks/check_session_settings.rb:118:in `check_secrets_yaml'
/Users/jpereira/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/brakeman-3.6.1/lib/brakeman/checks/check_session_settings.rb:31:in `run_check'
/Users/jpereira/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/brakeman-3.6.1/lib/brakeman/checks.rb:195:in `run_a_check'
/Users/jpereira/.rbenv/versions/2.4.3/lib/ruby/gems/2.4.0/gems/brakeman-3.6.1/lib/brakeman/checks.rb:131:in `block (2 levels) in actually_run_checks'
```

**Comment by presidentbeef** [comment]
Hi Jeff,

Although in your report you say you are using Brakeman 4.2.0, the stack trace you've provided is quite a bit older (3.6.1). I can't reproduce the issue with newer versions of Brakeman.
