### ISSUE TITLE
causing RSpec --only-failures to error out

### ISSUE THREAD

**Issue by mikeyduece** [presidentbeef/brakeman#1237]
### Background

Brakeman version: 4.3.0
Rails version: 5.2
Ruby version: 2.5

Link to Rails application code: (https://github.com/mikeyduece/bread_shop)

### Issue

```
Run options: include {:last_run_status=>"failed"}

All examples were filtered out

Randomized with seed 36778
must have 0 Critical Security Issues (FAILED - 1)

Coverage report generated for RSpec to /Users/mikeheft/turing/bread_shop/coverage. 174 / 249 LOC (69.88%) covered.
Traceback (most recent call last):
	18: from /Users/mikeheft/.rbenv/versions/2.5.0/bin/rspec:23:in `<main>'
	17: from /Users/mikeheft/.rbenv/versions/2.5.0/bin/rspec:23:in `load'
	16: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
	15: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
	14: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
	13: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:87:in `run'
	12: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:112:in `run_specs'
	11: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:81:in `report'
	10: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:171:in `finish'
	 9: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:191:in `close_after'
	 8: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:175:in `block in finish'
	 7: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `notify'
	 6: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:205:in `each'
	 5: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/reporter.rb:206:in `block in notify'
	 4: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/formatters/base_text_formatter.rb:32:in `dump_failures'
	 3: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `fully_formatted_failed_examples'
	 2: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each_with_index'
	 1: from /Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:113:in `each'
/Users/mikeheft/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rspec-core-3.7.1/lib/rspec/core/notifications.rb:114:in `block in fully_formatted_failed_examples': undefined method `fully_formatted' for #<RSpec::Core::Notifications::ExampleNotification:0x00007f890cc37cc8> (NoMethodError)
```

#### My Issue is Completely Different
I had opened an issue on rspec's repo. Here is a link to that issue. [My RSpec Issue](https://github.com/rspec/rspec-core/issues/2546#issuecomment-398463181) 
I deleted all my specs except one. And then started to remove gems. The first one I removed was brakeman. I also commented out the `require 'brakeman` in `rails_helper.rb` and commented out the following block of code. I'm not really sure how this could effect RSpec when running the `--only-failures` flag. Otherwise, I have no issues with this gem. I love using it. I just came across this and thought I'd bring it to your attention.

```ruby
config.after(:suite) do
  example_group = RSpec.describe('Brakeman Issues')
  example = example_group.example('must have 0 Critical Security Issues') do
    res = Brakeman.run app_path: "#{Rails.root}", outout_files = "#{serious}"
    serious=res.warnings.count { |w| w.confidence=0 }
    puts "\n\nBrakeman Result:\n Critical Security Issues = #{serious}"
    expect(serious).to eq(0)
  end
  example_group.run
  passed = example.execution_result.status = :passed
  RSpec.configuration.reporter.example.example_failed unless example passed
end
```

**Comment by presidentbeef** [comment]
Is this the exact code you had? It looks a little odd.

**Comment by presidentbeef** [comment]
This is a syntax error and typo:

```ruby
res = Brakeman.run app_path: "#{Rails.root}", outout_files = "#{serious}"
```

I'm assuming `outout_files = ` is intended to be `output_files:`. But then the value should be an array of file names, not a string. Also `serious` is not defined here but the next line assigns to it.

This also seems odd:
```ruby
passed = example.execution_result.status = :passed
RSpec.configuration.reporter.example.example_failed unless example passed
```

Why is it assigning the status?
Why are you calling `example` like it's a method in `unless example passed`?

Not sure if any of this has to do with why `--only-failures` is having problems, but hard to figure out without working code.

**Comment by mikeyduece** [comment]
Ya, my friend gave me that config block. I got rid of it as that was causing the error.
