### ISSUE TITLE
Error while running brakeman 4.3.1

### ISSUE THREAD

**Issue by ericproulx** [presidentbeef/brakeman#1249]
### Background

Brakeman version: 4.3.1
Rails version: 4.2.10
Ruby version: 2.3.7

Link to Rails application code: it's private sorry

### Issue

What problem are you seeing error while running

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
/Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/call_conversion_helper.rb:13:in `join_arrays': undefined method `concat' for nil:NilClass (NoMethodError)
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:207:in `process_call'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
        from (eval):3:in `map!'
        from (eval):3:in `map!'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:424:in `block in process_defs'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp_processor.rb:452:in `scope'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:422:in `process_defs'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:5:in `block in process_all'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:134:in `block in each_sexp'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each_sexp'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:4:in `process_all'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:36:in `process_class'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:5:in `block in process_all'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:134:in `block in each_sexp'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each_sexp'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:4:in `process_all'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:55:in `process_module'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:5:in `block in process_all'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:134:in `block in each_sexp'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each_sexp'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:4:in `process_all'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:55:in `process_module'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/processor.rb:57:in `process_model'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:293:in `process_model'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:288:in `block in process_models'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:302:in `block in track_progress'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:299:in `each'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:299:in `track_progress'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:286:in `process_models'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:57:in `process'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman.rb:354:in `scan'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman.rb:77:in `run'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:133:in `run_brakeman'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:118:in `regular_report'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:142:in `run_report'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:35:in `run'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:20:in `start'
        from /Users/eproulx/.rbenv/versions/2.3.7/lib/ruby/gems/2.3.0/gems/brakeman-4.3.1/bin/brakeman:8:in `<top (required)>'
        from /Users/eproulx/.rbenv/versions/2.3.7/bin/brakeman:22:in `load'
        from /Users/eproulx/.rbenv/versions/2.3.7/bin/brakeman:22:in `<main>'

```

**Comment by presidentbeef** [comment]
Hi @ericproulx, thanks for reporting this issue!

Can you trying #1251 and see if it resolves the problem? It would be nice to fix the root issue as well if you are able to narrow down the code to a test case you can share publicly. If not, no worries.

**Comment by ericproulx** [comment]
it works 🎊

**Comment by presidentbeef** [comment]
Thank you for confirming!
