### ISSUE TITLE
Error: Sexp#value called on multi-item Sexp in controller

### ISSUE THREAD

**Issue by clippermadness** [presidentbeef/brakeman#1291]
### Background

Brakeman version: 4.3.1
Rails version: 5.2
Ruby version: 2.4.1

### Issue

Brakeman appears to finish successfully and produces a report, but in the report has an "errors" section with stack trace.

From the full output, I think this is happening as it's processing a controller:

```
Processing DashboardsController
Processing DashboardsController#permissions_matrix
Rendering layouts/application (["DashboardsController#permissions_matrix"])
Rendering layouts/_header (["DashboardsController#permissions_matrix", "Template:layouts/application"])
Rendering notifications/_notification (["DashboardsController#permissions_matrix", "Template:layouts/application", "Template:layouts/_header"])
Rendering dashboards/permissions_matrix (["DashboardsController#permissions_matrix"])
[Notice] No such template: dashboards/permissions_matrix
Processing DashboardsController#index
Rendering dashboards/index (["DashboardsController#index"])
Rendering /layouts/_alert (["DashboardsController#index", "Template:dashboards/index"])
Rendering /dashboards/_video_count (["DashboardsController#index", "Template:dashboards/index"])
Sexp#value called on multi-item Sexp: `s(:call, s(:const, :Dashboard), :new, s(:hash, s(:lit, :org_unit), s(:call, nil, :get_current_org_unit)))`
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp.rb:54:in `value'
```

Stack trace:

```
== Errors ==

Error: Sexp#value called on multi-item Sexp: `s(:call, s(:const, :Dashboard), :new, s(:hash, s(:lit, :org_unit), s(:call, nil, :get_current_org_unit)))`
Location: /Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp.rb:54:in `value'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:96:in `block in process_template'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/util.rb:98:in `block in hash_iterate'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/util.rb:97:in `step'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/util.rb:97:in `hash_iterate'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:95:in `process_template'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/template_alias_processor.rb:30:in `process_template'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:45:in `process_partial'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:20:in `process_render'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:51:in `process_safely'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:131:in `process_template'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/controller_alias_processor.rb:191:in `process_template'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:51:in `process_action'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/render_helper.rb:12:in `process_render'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:378:in `block in process_iter'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp_processor.rb:452:in `scope'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:344:in `process_iter'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/controller_alias_processor.rb:130:in `process_iter'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:376:in `block in process_iter'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp_processor.rb:452:in `scope'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:344:in `process_iter'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/controller_alias_processor.rb:130:in `process_iter'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:5:in `block in process_all'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:134:in `block in each_sexp'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp.rb:131:in `each_sexp'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/lib/processor_helper.rb:4:in `process_all'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/controller_alias_processor.rb:97:in `block in process_defn'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:413:in `block in meth_env'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bundle/ruby/2.5.0/gems/sexp_processor-4.11.0/lib/sexp_processor.rb:452:in `scope'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:410:in `meth_env'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/controller_alias_processor.rb:90:in `process_defn'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processors/controller_alias_processor.rb:31:in `process_controller'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/processor.rb:51:in `process_controller_alias'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:241:in `block (2 levels) in process_controller_data_flows'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:240:in `each'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:240:in `block in process_controller_data_flows'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:302:in `block in track_progress'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:299:in `each'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:299:in `track_progress'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:238:in `process_controller_data_flows'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/scanner.rb:61:in `process'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman.rb:354:in `scan'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman.rb:77:in `run'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:133:in `run_brakeman'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:118:in `regular_report'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:142:in `run_report'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:35:in `run'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/lib/brakeman/commandline.rb:20:in `start'
/Users/rich/.rvm/gems/ruby-2.4.1/gems/brakeman-4.3.1/bin/brakeman:8:in `<top (required)>'
/Users/rich/.rvm/gems/ruby-2.4.1/bin/brakeman:23:in `load'
/Users/rich/.rvm/gems/ruby-2.4.1/bin/brakeman:23:in `<main>'
/Users/rich/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/rich/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by presidentbeef** [comment]
Hi Rich,

It looks like perhaps you have a call to `render ..., locals: ...` where the `locals` are not a hash value, or one of the keys is not a symbol? Does that sound right?

**Comment by clippermadness** [comment]
Hey Justin - yes that appears to be it. In the /dashboards/_video_count file I have this line:
`render partial: '/dashboards/video_count', locals: {@dash=> @dash}`

Which probably should be:
`render partial: '/dashboards/video_count', locals: {dash: @dash}`

`@dash` is a model object

**Comment by clippermadness** [comment]
And I can confirm that after making that fix in my code brakeman no longer reports a crash.
