### ISSUE TITLE
Nil error in render_helper.rb

### ISSUE THREAD

**Issue by arothian** [presidentbeef/brakeman#1350]
### Background

Brakeman version: 4.5.0
Rails version: 4.2.11.1
Ruby version: 2.6.3

Link to Rails application code: N/A

### Issue

Brakeman fails and reports an error trying to append to a nil value. I'm sure its some weird coding bit triggering this. I can't share my codebase, but suggestions on tracking down the particular code section so I can give a reproducible test case welcome.

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
== Errors ==
Error: no implicit conversion of nil into String
Location: /Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/lib/render_helper.rb:44:in `+'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/lib/render_helper.rb:44:in `process_partial'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/lib/render_helper.rb:20:in `process_render'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:51:in `process_safely'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/lib/render_helper.rb:136:in `process_template'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/template_alias_processor.rb:32:in `process_template'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/lib/render_helper.rb:45:in `process_partial'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/lib/render_helper.rb:20:in `process_render'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:63:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:61:in `process_default'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processors/alias_processor.rb:51:in `process_safely'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/processor.rb:87:in `process_template_alias'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/scanner.rb:282:in `block in process_template_data_flows'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/scanner.rb:306:in `block in track_progress'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/scanner.rb:303:in `each'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/scanner.rb:303:in `track_progress'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/scanner.rb:280:in `process_template_data_flows'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/scanner.rb:56:in `process'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman.rb:354:in `scan'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman.rb:77:in `run'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/commandline.rb:133:in `run_brakeman'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/commandline.rb:118:in `regular_report'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/commandline.rb:142:in `run_report'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/commandline.rb:35:in `run'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/lib/brakeman/commandline.rb:20:in `start'
/Users//.rvm/gems/ruby-2.6.3/gems/brakeman-4.5.0/bin/brakeman:10:in `<top (required)>'
/Users//.rvm/gems/ruby-2.6.3/bin/brakeman:23:in `load'
/Users//.rvm/gems/ruby-2.6.3/bin/brakeman:23:in `<main>'
```

**Comment by presidentbeef** [comment]
Hi Kevin,

Thank you for the report!

If you watch the debug output carefully, you should be able to see which template is triggering the exception. It's often easiest to output to a file and check it out there:

```
brakeman test/apps/rails2/ --no-progress -d &> output
```

From a preliminary glance, it looks like you may be calling `render` or `layout` in a template with a value like `"/"`?

**Comment by arothian** [comment]
Appreciated the debug steps. It is indeed a `render` call.

It looks like this `<%= render(:partial => nested_partial) if nested_partial.present? %>`. 

Where `nested_partial` is actually passed into this template via other render calls in different template, (e.g. `<%= render :partial => 'shared_template', :locals => {:nested_partial => ''} %>`)

**Comment by arothian** [comment]
Thanks!
