### ISSUE TITLE
Valid HAML multiline comment produces "Inconsistent indentation" error

### ISSUE THREAD

**Issue by jaredbeck** [presidentbeef/brakeman#1370]
### Background

Brakeman version: 4.5.1
Rails version: 5.2.3
Ruby version: 2.6.3

Rails application code: 

```
%p
  -# this comment spans multiple lines.
     Comment lines 2..n are indented with 5 spaces.
     This comment style is valid HAML.
  The comment has ended, we're back to 2 spaces of indentation.
```

See [HAML documentation](http://haml.info/docs/yardoc/file.REFERENCE.html#haml-comments--)

### Issue

```
Error: Inconsistent indentation: 5 spaces used for indentation, but the rest of the document was indented using 2 spaces.
Location: While compiling HAML in /Users/jared/.../redacted.html.haml
```

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
Error: Inconsistent indentation: 5 spaces used for indentation, but the rest of the document was indented using 2 spaces.
Location: While compiling HAML in /Users/jared/.../redacted.html.haml
/Users/jared/.../redacted.html.haml:999
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:174:in `block in tabs'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:152:in `instance_eval'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:152:in `tabs'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:751:in `block_opened?'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:326:in `haml_comment'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:284:in `silent_script'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:225:in `process_line'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb:121:in `parse'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/engine.rb:66:in `initialize'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/parsers/template_parser.rb:80:in `new'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/parsers/template_parser.rb:80:in `parse_haml'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/parsers/template_parser.rb:27:in `parse_template'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/scanner.rb:87:in `block in parse_files'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/file_parser.rb:29:in `block in read_files'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/file_parser.rb:26:in `each'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/file_parser.rb:26:in `read_files'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/scanner.rb:86:in `parse_files'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/scanner.rb:45:in `process'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman.rb:361:in `scan'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman.rb:80:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/commandline.rb:133:in `run_brakeman'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/commandline.rb:118:in `regular_report'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/commandline.rb:142:in `run_report'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/commandline.rb:35:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/lib/brakeman/commandline.rb:20:in `start'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/brakeman-4.5.1/bin/brakeman:10:in `<top (required)>'
/Users/jared/.rbenv/versions/2.6.3/bin/brakeman:23:in `load'
/Users/jared/.rbenv/versions/2.6.3/bin/brakeman:23:in `<top (required)>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `load'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:74:in `kernel_load'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli/exec.rb:28:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:463:in `exec'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:27:in `dispatch'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/cli.rb:18:in `start'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:30:in `block in <top (required)>'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/Users/jared/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/bundler-2.0.1/exe/bundle:22:in `<top (required)>'
/Users/jared/.rbenv/versions/2.6.3/bin/bundle:23:in `load'
/Users/jared/.rbenv/versions/2.6.3/bin/bundle:23:in `<main>'
```

**Comment by jaredbeck** [comment]
My application uses haml 5, but looking at the stack trace it seems brakeman is using the haml 4 parser, so maybe that's the issue?

```
/Users/jared/.../gems/brakeman-4.5.1/bundle/ruby/2.5.0/gems/haml-4.0.7/lib/haml/parser.rb...
```

**Comment by presidentbeef** [comment]
Yes, I think that's probably the issue.

Unfortunately haml 5 is a big change from haml 4, so it's not trivial to update.

**Comment by jaredbeck** [comment]
> Unfortunately haml 5 is a big change from haml 4, so it's not trivial to update.

Understandable. If it's going to take a long time to support haml 5, maybe brakeman could detect the haml version and raise an error if said version is not supported. I'd be willing to try implementing that.

**Comment by presidentbeef** [comment]
> raise an error if said version is not supported.

You mean an error in the report? Or just a notification message?

There are facilities for checking gems in use and their versions in [Tracker::Config](https://github.com/presidentbeef/brakeman/blob/master/lib/brakeman/tracker/config.rb).

**Comment by jaredbeck** [comment]
>> maybe .. raise an error if said version is not supported.

> You mean an error in the report? Or just a notification message?

Whatever you think is best. If brakeman can still provide some value, then a warning is ok. If it cannot provide any value, then it should probably just `exit`.

**Comment by presidentbeef** [comment]
Majority applications using Haml seem to scan just fine with Haml 4.x, so it definitely should not be a fatal error.

**Comment by jaredbeck** [comment]
Historical note: When haml 5 was released in 2017, updating the brakeman dependency was discussed in https://github.com/presidentbeef/brakeman/pull/1043

> Brakeman depends on the internal compiler output of Haml/Slim/ERB, so updates like this are problematic. (https://github.com/presidentbeef/brakeman/pull/1043#issuecomment-300211072)
