### ISSUE TITLE
Sexp#value called on multi-item Sexp

### ISSUE THREAD

**Issue by anaumov** [presidentbeef/brakeman#1465]
### Background

Brakeman version: 4.8.0
Rails version: 6.0.2.1
Ruby version: 2.7.0

Link to Rails application code: https://gist.github.com/anaumov/b9e6d0d04d56af1c5f3e698879bd1e69

### Issue
What problem are you seeing?

After running brakeman I got an error
```
Error: Sexp#value called on multi-item Sexp: `s(:call, s(:call, s(:call, nil, :model_name), :pluralize), :to_sym)`
Location: /Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp.rb:54:in `value'
```

I guess it's dupe https://github.com/presidentbeef/brakeman/issues/1291 but I'not clear about an error. I looked into documentation but didn't find an explanation. Why it's bad practice to use variables instead of a symbols in the controller?

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
Error: Sexp#value called on multi-item Sexp: `s(:call, s(:call, s(:call, nil, :model_name), :pluralize), :to_sym)`
Location: /Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp.rb:54:in `value'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/lib/render_helper.rb:101:in `block in process_template'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/util.rb:102:in `block in hash_iterate'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/util.rb:101:in `step'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/util.rb:101:in `hash_iterate'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/lib/render_helper.rb:100:in `process_template'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/controller_alias_processor.rb:194:in `process_template'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/lib/render_helper.rb:15:in `process_render'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/lib/processor_helper.rb:5:in `block in process_all'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/bundle/ruby/2.7.0/gems/sexp_processor-4.14.1/lib/sexp.rb:142:in `block in each_sexp'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/bundle/ruby/2.7.0/gems/sexp_processor-4.14.1/lib/sexp.rb:139:in `each'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/bundle/ruby/2.7.0/gems/sexp_processor-4.14.1/lib/sexp.rb:139:in `each_sexp'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/lib/processor_helper.rb:4:in `process_all'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/controller_alias_processor.rb:100:in `block in process_defn'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/alias_processor.rb:430:in `block in meth_env'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/bundle/ruby/2.7.0/gems/sexp_processor-4.14.1/lib/sexp_processor.rb:452:in `scope'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/alias_processor.rb:427:in `meth_env'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/controller_alias_processor.rb:93:in `process_defn'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/alias_processor.rb:62:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/alias_processor.rb:60:in `process_default'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processors/controller_alias_processor.rb:31:in `process_controller'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/processor.rb:50:in `process_controller_alias'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:250:in `block (2 levels) in process_controller_data_flows'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:249:in `each'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:249:in `block in process_controller_data_flows'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:311:in `block in track_progress'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:308:in `each'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:308:in `track_progress'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:247:in `process_controller_data_flows'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/scanner.rb:61:in `process'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman.rb:365:in `scan'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman.rb:80:in `run'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/commandline.rb:133:in `run_brakeman'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/commandline.rb:118:in `regular_report'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/commandline.rb:142:in `run_report'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/commandline.rb:35:in `run'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/lib/brakeman/commandline.rb:20:in `start'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/brakeman-4.8.0/bin/brakeman:10:in `<top (required)>'
/Users/naumov/.rbenv/versions/2.7.0/bin/brakeman:23:in `load'
/Users/naumov/.rbenv/versions/2.7.0/bin/brakeman:23:in `<top (required)>'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/Users/naumov/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/Users/naumov/.rbenv/versions/2.7.0/bin/bundle:23:in `load'
/Users/naumov/.rbenv/versions/2.7.0/bin/bundle:23:in `<main>'
```

**Comment by presidentbeef** [comment]
Thank you for reporting!

**Comment by anaumov** [comment]
@presidentbeef can you tell why it's bad practice to use variables instead of symbols in the controller?

**Comment by presidentbeef** [comment]
@anaumov I am not sure I understand your question. The issue here was that Brakeman was assuming the keys in the `locals` Hash would be symbols.

**Comment by anaumov** [comment]
@presidentbeef why it's bad?
```
property = :user
{ property => User.last }
```
