### ISSUE TITLE
superclass mismatch for class Mark

### ISSUE THREAD

**Issue by akimd** [presidentbeef/brakeman#1543]
### Background

Brakeman version: 4.10.0
Rails version: 6.0.3.4
Ruby version: 2.5.7p206

Link to Rails application code: private, sorry.

### Issue

What problem are you seeing?

In my logs, I have an error:
```
  "errors": [
    {
      "error": "undefined method `force_encoding' for #<Brakeman::FilePath:0x000055b662474f50> While processing /home/solutions/reference_dev/reference_dev/app/views/commandes/test_model.html.erb",
      "location": "/opt/ruby-2.5.7/lib/ruby/gems/2.5.0/gems/brakeman-4.10.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.0/lib/ruby_parser_extras.rb:604:in `literal_concat'"
    },
    {
      "error": "superclass mismatch for class Mark",
      "location": "/opt/ruby-2.5.7/lib/ruby/2.5.0/psych/parser.rb:34:in `<class:Parser>'"
    }
  ],
```

I have created #1542 for the first error.  This issue is about the Mark stuff.  It appears to be related to Psych, and is already the topic of issues elsewhere (e.g., https://github.com/rubocop-hq/rubocop/issues/6781).

Cheers!

**Comment by presidentbeef** [comment]
This looks like an issue with a particular version of Ruby? 2.5 is EOL next month.

**Comment by BobbyMcWho** [comment]
I'm seeing the latter error w/ ruby 2.6 and the latest  released version of brakeman
