### ISSUE TITLE
Argument Forwarding Parse Error on Value "..."

### ISSUE THREAD

**Issue by ksylvest** [presidentbeef/brakeman#1559]
### Background

Brakeman version: 5.0.0
Rails version: 6.1.1
Ruby version: 3.0.0

Link to Rails application code: N/A

### Issue

Given a snippet using [argument forwarding](https://blog.saeloun.com/2019/12/04/ruby-2-7-adds-new-operator-for-arguments-forwarding.html):

```ruby
def greet(name)
  puts "Welcome #{name}"
end

def howdy(...)
  greet(...)
end
```

Attempting to run brakeman causes a parsing error:

```
Error: demo.rb:5 :: parse error on value "..." (tDOT3) Could not parse demo.rb
Location: /Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
```

#### Other Error

Stack trace:

```
Error: demo.rb:5 :: parse error on value "..." (tDOT3) Could not parse demo.rb
Location: /Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser_extras.rb:1304:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser_extras.rb:1329:in `block in process'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/timeout.rb:35:in `catch'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/timeout.rb:35:in `catch'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser_extras.rb:1317:in `process'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser.rb:36:in `block in process'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser.rb:33:in `each'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser.rb:33:in `process'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/file_parser.rb:43:in `parse_ruby'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/file_parser.rb:17:in `block in parse_files'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/file_parser.rb:27:in `block in read_files'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/file_parser.rb:24:in `each'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/file_parser.rb:24:in `read_files'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/file_parser.rb:16:in `parse_files'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/scanner.rb:76:in `parse_files'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/scanner.rb:49:in `process'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman.rb:379:in `scan'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman.rb:85:in `run'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/commandline.rb:157:in `run_brakeman'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/commandline.rb:125:in `regular_report'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/commandline.rb:166:in `run_report'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/commandline.rb:35:in `run'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/lib/brakeman/commandline.rb:20:in `start'
/Users/kevin/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/brakeman-5.0.0/bin/brakeman:10:in `<top (required)>'
/Users/kevin/.rbenv/versions/3.0.0/bin/brakeman:23:in `load'
/Users/kevin/.rbenv/versions/3.0.0/bin/brakeman:23:in `<main>'
```

**Comment by presidentbeef** [comment]
Yes, Brakeman depends on RubyParser and it does not support this syntax yet https://github.com/seattlerb/ruby_parser/issues/309

You can use `--skip-files` to avoid the error for the given file(s).
