### ISSUE TITLE
Permission denied error while trying to generate html report from Docker

### ISSUE THREAD

**Issue by ShockwaveNN** [presidentbeef/brakeman#1560]
### Background

Brakeman version: 5.0.0
Rails version: 6.1.1
Ruby version: ??? provided by default docker

Link to Rails application code: https://github.com/ONLYOFFICE/testing-wrata/
But I think project is not related

### Issue

Run brakeman in docker with html report as said in README.md
```
docker run -v "$(pwd)":/code presidentbeef/brakeman -o brakeman_results.html
```
brakeman is running, but resulting error on report finalization:
```
Generating report...
/usr/src/app/lib/brakeman.rb:414:in `initialize': Permission denied @ rb_sysopen - brakeman_results.html (Errno::EACCES)
        from /usr/src/app/lib/brakeman.rb:414:in `open'
        from /usr/src/app/lib/brakeman.rb:414:in `block in write_report_to_files'
        from /usr/src/app/lib/brakeman.rb:408:in `each'
        from /usr/src/app/lib/brakeman.rb:408:in `each_with_index'
        from /usr/src/app/lib/brakeman.rb:408:in `write_report_to_files'
        from /usr/src/app/lib/brakeman.rb:394:in `scan'
        from /usr/src/app/lib/brakeman.rb:85:in `run'
        from /usr/src/app/lib/brakeman/commandline.rb:157:in `run_brakeman'
        from /usr/src/app/lib/brakeman/commandline.rb:125:in `regular_report'
        from /usr/src/app/lib/brakeman/commandline.rb:166:in `run_report'
        from /usr/src/app/lib/brakeman/commandline.rb:35:in `run'
        from /usr/src/app/lib/brakeman/commandline.rb:20:in `start'
        from /usr/src/app/bin/brakeman:10:in `<main>'
```
![image](https://user-images.githubusercontent.com/668524/106154180-643f7f80-6190-11eb-9280-f7c597f3938b.png)

Seems like some kind of permission issue, I can provide some more info, but there is no strange permission applied to my current working directory

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Cannot do in Docker

**Comment by carlosjpr-collab** [comment]
I see the same pb
![image](https://user-images.githubusercontent.com/38086105/115786697-744ab200-a3c1-11eb-8719-44c125accc51.png)

**Comment by ShockwaveNN** [comment]
@jympetalmd Nope, sorry, your variant (with adding `\` to break lines) still does not work for me with the same error

```
docker run \
-v "$(pwd)":/code:ro \
-v /tmp:/tmp \
presidentbeef/brakeman \
-o brakeman_results.html
....
/usr/src/app/lib/brakeman.rb:427:in `initialize': Read-only file system @ rb_sysopen - brakeman_results.html (Errno::EROFS)
	from /usr/src/app/lib/brakeman.rb:427:in `open'
	from /usr/src/app/lib/brakeman.rb:427:in `block in write_report_to_files'
	from /usr/src/app/lib/brakeman.rb:421:in `each'
	from /usr/src/app/lib/brakeman.rb:421:in `each_with_index'
	from /usr/src/app/lib/brakeman.rb:421:in `write_report_to_files'
	from /usr/src/app/lib/brakeman.rb:407:in `scan'
	from /usr/src/app/lib/brakeman.rb:86:in `run'
	from /usr/src/app/lib/brakeman/commandline.rb:157:in `run_brakeman'
	from /usr/src/app/lib/brakeman/commandline.rb:125:in `regular_report'
	from /usr/src/app/lib/brakeman/commandline.rb:166:in `run_report'
	from /usr/src/app/lib/brakeman/commandline.rb:35:in `run'
	from /usr/src/app/lib/brakeman/commandline.rb:20:in `start'
	from /usr/src/app/bin/brakeman:10:in `<main>'
```

**Comment by jympetalmd** [comment]
> @jympetalmd Nope, sorry, your variant (with adding `\` to break lines) still does not work for me with the same error
> 
> ```
> docker run \
> -v "$(pwd)":/code:ro \
> -v /tmp:/tmp \
> presidentbeef/brakeman \
> -o brakeman_results.html
> ....
> /usr/src/app/lib/brakeman.rb:427:in `initialize': Read-only file system @ rb_sysopen - brakeman_results.html (Errno::EROFS)
> 	from /usr/src/app/lib/brakeman.rb:427:in `open'
> 	from /usr/src/app/lib/brakeman.rb:427:in `block in write_report_to_files'
> 	from /usr/src/app/lib/brakeman.rb:421:in `each'
> 	from /usr/src/app/lib/brakeman.rb:421:in `each_with_index'
> 	from /usr/src/app/lib/brakeman.rb:421:in `write_report_to_files'
> 	from /usr/src/app/lib/brakeman.rb:407:in `scan'
> 	from /usr/src/app/lib/brakeman.rb:86:in `run'
> 	from /usr/src/app/lib/brakeman/commandline.rb:157:in `run_brakeman'
> 	from /usr/src/app/lib/brakeman/commandline.rb:125:in `regular_report'
> 	from /usr/src/app/lib/brakeman/commandline.rb:166:in `run_report'
> 	from /usr/src/app/lib/brakeman/commandline.rb:35:in `run'
> 	from /usr/src/app/lib/brakeman/commandline.rb:20:in `start'
> 	from /usr/src/app/bin/brakeman:10:in `<main>'
> ```

Sorry forgot to add /tmp to the -o output path:     -o /tmp/brakeman_results.html
