### ISSUE TITLE
Error with one liner method

### ISSUE THREAD

**Issue by dawidof** [presidentbeef/brakeman#1593]
### Background

Brakeman version: brakeman 5.0.1
Rails version: Rails 6.1.3.2
Ruby version: ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

Link to Rails application code: ?

### Issue

What problem are you seeing?
`def say_hello() = puts("Hello World!")`
```
Error: app/services/reports/single_medium.rb:33 :: parse error on value "=" (tEQL) Could not parse app/services/reports/single_medium.rb
Location: /usr/local/lib/ruby/gems/3.0.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
/usr/local/lib/ruby/3.0.0/timeout.rb:97:in `block in timeout'
/usr/local/lib/ruby/3.0.0/timeout.rb:35:in `block in catch'
/usr/local/lib/ruby/3.0.0/timeout.rb:35:in `catch'
/usr/local/lib/ruby/3.0.0/timeout.rb:35:in `catch'
/usr/local/lib/ruby/3.0.0/timeout.rb:112:in `timeout'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser_extras.rb:1317:in `process'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser.rb:36:in `block in process'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser.rb:33:in `each'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser.rb:33:in `process'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/file_parser.rb:43:in `parse_ruby'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/file_parser.rb:17:in `block in parse_files'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/file_parser.rb:27:in `block in read_files'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/file_parser.rb:24:in `each'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/file_parser.rb:24:in `read_files'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/file_parser.rb:16:in `parse_files'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/scanner.rb:76:in `parse_files'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/scanner.rb:49:in `process'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman.rb:386:in `scan'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman.rb:85:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/commandline.rb:157:in `run_brakeman'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/commandline.rb:125:in `regular_report'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/commandline.rb:166:in `run_report'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/commandline.rb:35:in `run'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/lib/brakeman/commandline.rb:20:in `start'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bin/brakeman:10:in `<top (required)>'
/usr/local/bin/brakeman:23:in `load'
/usr/local/bin/brakeman:23:in `<main>'
```

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
Error: app/services/reports/single_medium.rb:33 :: parse error on value "=" (tEQL) Could not parse app/services/reports/single_medium.rb
Location: /usr/local/lib/ruby/gems/3.0.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser_extras.rb:1304:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
/usr/local/lib/ruby/gems/3.0.0/gems/brakeman-5.0.1/bundle/ruby/2.7.0/gems/ruby_parser-3.15.1/lib/ruby_parser_extras.rb:1329:in `block in process'
```

**Comment by presidentbeef** [comment]
Yes, ruby_parser does not support this syntax yet.

**Comment by ThePadawan** [comment]
See corresponding ruby_parser issue here: https://github.com/seattlerb/ruby_parser/issues/320
