### ISSUE TITLE
Error: undefined method `line' for nil:NilClass

### ISSUE THREAD

**Issue by orien** [presidentbeef/brakeman#1609]
### Background

Brakeman version: 5.0.2
Rails version: 5.2.6
Ruby version: 2.6.6

Link to Rails application code: TODO

### Issue

Brakeman fails with the error:

> Error: undefined method 'line' for nil:NilClass
> Location: [/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:397](https://github.com/presidentbeef/brakeman/blob/v5.0.2/lib/brakeman/processors/alias_processor.rb#L397):in `join_item'

<details><summary>Backtrace (click me)</summary>

```
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:397:in `join_item'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:342:in `block in process_array_join'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:341:in `each'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:341:in `process_array_join'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:304:in `process_call'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:62:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:60:in `process_default'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:178:in `process_call'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:466:in `block in process_iter'
/usr/local/bundle/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/sexp_processor-4.15.3/lib/sexp_processor.rb:452:in `scope'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:427:in `process_iter'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:491:in `block in process_defn'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:501:in `block in meth_env'
/usr/local/bundle/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/sexp_processor-4.15.3/lib/sexp_processor.rb:452:in `scope'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:498:in `meth_env'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:490:in `process_defn'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/alias_processor.rb:50:in `process_safely'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/library_processor.rb:37:in `process_defn'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/lib/module_helper.rb:54:in `handle_class'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/library_processor.rb:25:in `process_class'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/usr/local/bundle/gems/brakeman-5.0.2/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processors/library_processor.rb:21:in `process_library'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/processor.rb:98:in `process_lib'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:243:in `process_lib'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:237:in `block in process_libs'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:340:in `block in track_progress'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:337:in `each'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:337:in `track_progress'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:235:in `process_libs'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:55:in `process'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman.rb:390:in `scan'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman.rb:85:in `run'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:157:in `run_brakeman'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:125:in `regular_report'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:166:in `run_report'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:35:in `run'
/usr/local/bundle/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:20:in `start'
/usr/local/bundle/gems/brakeman-5.0.2/bin/brakeman:10:in `<top (required)>'
/usr/local/bundle/bin/brakeman:23:in `load'
/usr/local/bundle/bin/brakeman:23:in `<main>'
```

</details>

**Comment by orien** [comment]
I didn't get time to identify the code in my project that triggered this issue. Version 5.0.4 seems to resolve it. Thanks.

**Comment by presidentbeef** [comment]
@orien 5.0.4 only fixes it because there were unintended changes in the 5.0.2/5.03 releases.

If you could provide a code sample to reproduce the issue, that would be great.

It should be related to calling `join` somewhere on an array.

**Comment by wbowling** [comment]
Here is a minimal controller that triggers the issue:
```ruby
class SampleController < ApplicationController
  def index
    params.values_at(:test).join("|")
  end
end
```
