### ISSUE TITLE
brakeman 5.0.2 triggers racc error

### ISSUE THREAD

**Issue by modosc** [presidentbeef/brakeman#1610]
### Background

Brakeman version: 5.0.2
Rails version: 6.0
Ruby version: 2.7.2

### Issue
this code parsed fine in brakeman 5.0.1:

```
      def self.on_waiting(...)
       # code here doesn't matter
      end
```
 but causes this error with 5.0.2:
```
Error: lib/task_machine/tasks/abstract_sub_task_delegate.rb:40 :: parse error on value "..." (tBDOT3) Could not parse lib/task_machine/tasks/abstract_sub_task_delegate.rb
Location: /Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/racc-1.5.2/lib/racc/parser.rb:538:in `on_error'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/ruby_parser-3.16.0/lib/ruby_parser_extras.rb:1304:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/ruby_parser-3.16.0/lib/ruby_parser_extras.rb:1329:in `block in process'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:95:in `block in timeout'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `block in catch'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:33:in `catch'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/2.7.0/timeout.rb:110:in `timeout'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/ruby_parser-3.16.0/lib/ruby_parser_extras.rb:1317:in `process'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/ruby_parser-3.16.0/lib/ruby_parser.rb:36:in `block in process'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/ruby_parser-3.16.0/lib/ruby_parser.rb:33:in `each'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/ruby_parser-3.16.0/lib/ruby_parser.rb:33:in `process'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/file_parser.rb:70:in `parse_ruby'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/file_parser.rb:33:in `block in parse_files'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:507:in `call_with_index'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:477:in `process_incoming_jobs'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:459:in `block in worker'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `fork'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:450:in `worker'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:441:in `block in create_workers'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `each_with_index'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:440:in `create_workers'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:380:in `work_in_processes'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bundle/ruby/2.7.0/gems/parallel-1.20.1/lib/parallel.rb:283:in `map'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/file_parser.rb:28:in `parse_files'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:76:in `parse_files'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/scanner.rb:49:in `process'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman.rb:390:in `scan'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman.rb:85:in `run'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:157:in `run_brakeman'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:125:in `regular_report'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:166:in `run_report'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:35:in `run'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/lib/brakeman/commandline.rb:20:in `start'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/brakeman-5.0.2/bin/brakeman:10:in `<top (required)>'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/bin/brakeman:23:in `load'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/bin/brakeman:23:in `<top (required)>'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `load'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:63:in `kernel_load'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli/exec.rb:28:in `run'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:494:in `exec'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:30:in `dispatch'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/cli.rb:24:in `start'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/exe/bundle:49:in `block in <top (required)>'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/lib/bundler/friendly_errors.rb:130:in `with_friendly_errors'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bundler-2.2.16/exe/bundle:37:in `<top (required)>'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/bin/bundle:23:in `load'
/Users/jonathan.schatz/.rbenv/versions/2.7.2/bin/bundle:23:in `<main>'

No warnings found
```

**Comment by presidentbeef** [comment]
OHHHHH oops. I'll get out a release to address this.

**Comment by modosc** [comment]
seems to work now with `5.0.4`, thanks!
