### ISSUE TITLE
Brakeman fails with: NoMethodError: undefined method `line' for nil:NilClass

### ISSUE THREAD

**Issue by parkerfinch** [presidentbeef/brakeman#1635]
### Background

Brakeman version: 5.1.1

This issue does not occur at abe7684 but does occur at 2c086d4, so presumably the bug was introduced somewhere in there.

Rails version: 6.1.3.2
Ruby version: 2.6.6

Link to Rails application code: Code is not in a public repo.

### Issue

Brakeman is unable to complete successfully and fails with the backtrace below.
It fails on a file that includes something like:
```
{
  somekey: :someval,
  some_other_key: :some_other_val
}.values_at(*PRIMARY_KEY).join("$")
```

Brakeman completes successfully if I change the code to either:
```
{
  somekey: :someval,
  some_other_key: :some_other_val
}.values_at(*PRIMARY_KEY)
```
or
```
{
  somekey: :someval,
  some_other_key: :some_other_val
}.values_at(:literal1, :literal2).join("$")
```

so it seems like it is the combination of the splat and join that is leading to issues.

Let me know what other info I can provide!

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

I did not need to run with `--debug`, the stack trace is printed in normal operation. The `--debug` option was helpful for determining which file it was failing on, however.

Output of `bundle exec brakeman`:
```
Loading scanner...
Processing application in /Users/<project_path>
Processing gems...
[Notice] Detected Rails 6 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Detecting file types...
Processing initializers...
Processing libs...ssed
bundler: failed to load command: brakeman (/Users/redacted/.gem/ruby/2.6.6/bin/brakeman)
NoMethodError: undefined method `line' for nil:NilClass
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:370:in `join_item'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:324:in `block in process_array_join'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:323:in `each'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:323:in `process_array_join'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:292:in `process_call'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
  (eval):3:in `map!'
  (eval):3:in `map!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:464:in `block in process_defn'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:474:in `block in meth_env'
  /Users/xxx/.gem/ruby/2.6.6/gems/sexp_processor-4.15.3/lib/sexp_processor.rb:452:in `scope'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:471:in `meth_env'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:463:in `process_defn'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/alias_processor.rb:50:in `process_safely'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/library_processor.rb:37:in `process_defn'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
  (eval):3:in `map!'
  (eval):3:in `map!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/module_helper.rb:54:in `handle_class'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/library_processor.rb:25:in `process_class'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
  (eval):3:in `map!'
  (eval):3:in `map!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/module_helper.rb:22:in `handle_module'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/library_processor.rb:29:in `process_module'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
  (eval):3:in `map!'
  (eval):3:in `map!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/module_helper.rb:22:in `handle_module'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/library_processor.rb:29:in `process_module'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
  (eval):3:in `map!'
  (eval):3:in `map!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/lib/module_helper.rb:22:in `handle_module'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/library_processor.rb:29:in `process_module'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processors/library_processor.rb:21:in `process_library'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/processor.rb:98:in `process_lib'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:243:in `process_lib'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:237:in `block in process_libs'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:340:in `block in track_progress'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:337:in `each'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:337:in `track_progress'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:235:in `process_libs'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/scanner.rb:55:in `process'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman.rb:390:in `scan'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman.rb:85:in `run'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/commandline.rb:157:in `run_brakeman'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/commandline.rb:125:in `regular_report'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/commandline.rb:166:in `run_report'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/commandline.rb:35:in `run'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/lib/brakeman/commandline.rb:20:in `start'
  /Users/xxx/.gem/ruby/2.6.6/bundler/gems/brakeman-2c086d45d3bc/bin/brakeman:10:in `<top (required)>'
  /Users/xxx/.gem/ruby/2.6.6/bin/brakeman:23:in `load'
  /Users/xxx/.gem/ruby/2.6.6/bin/brakeman:23:in `<top (required)>'
```

**Comment by Capncavedan** [comment]
I am also experiencing this error with Brakeman 5.1.1 when attempting to upgrade from 5.0.4

Ruby 2.5.7, Rails 6.0.3.7

My brakeman run completes, but I get something in the "Errors" section:

```
== Errors ==

Error: undefined method `line' for nil:NilClass
Location: /Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:406:in `join_item'
```

And if I run with `--debug` I get a lot more:

```
== Errors ==

Error: undefined method `line' for nil:NilClass
Location: /Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:406:in `join_item'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:351:in `block in process_array_join'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:350:in `each'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:350:in `process_array_join'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:313:in `process_call'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:62:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:60:in `process_default'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:686:in `process_hash'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:62:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:60:in `process_default'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:178:in `process_call'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:62:in `block in process_default'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:60:in `process_default'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:686:in `process_hash'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:500:in `block in process_defn'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:510:in `block in meth_env'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/bundle/ruby/2.7.0/gems/sexp_processor-4.15.3/lib/sexp_processor.rb:452:in `scope'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:507:in `meth_env'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:499:in `process_defn'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/alias_processor.rb:50:in `process_safely'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/library_processor.rb:37:in `process_defn'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
(eval):3:in `map!'
(eval):3:in `map!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/lib/module_helper.rb:22:in `handle_module'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/library_processor.rb:29:in `process_module'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processors/library_processor.rb:21:in `process_library'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/processor.rb:98:in `process_lib'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:243:in `process_lib'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:237:in `block in process_libs'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:340:in `block in track_progress'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:337:in `each'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:337:in `track_progress'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:235:in `process_libs'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:55:in `process'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman.rb:392:in `scan'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman.rb:86:in `run'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:157:in `run_brakeman'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:125:in `regular_report'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:166:in `run_report'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:35:in `run'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:20:in `start'
/Users/xxx/vendor/bundle/ruby/2.5.0/gems/brakeman-5.1.1/bin/brakeman:10:in `<top (required)>'
/Users/xxx/vendor/bundle/ruby/2.5.0/bin/brakeman:23:in `load'
/Users/xxx/vendor/bundle/ruby/2.5.0/bin/brakeman:23:in `<main>'
/Users/xxx/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `eval'
/Users/xxx/vendor/bundle/ruby/2.5.0/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by presidentbeef** [comment]
Thanks for the detailed information.

Unfortunately I cannot reproduce this issue with the code given. Although `join` is triggering the issue, it's caused by something earlier, probably when splatting the array values. But it's all working for me.

**Comment by Chris-Brauns-II** [comment]
I am also experiencing this bug. Was able to create a example repo that should let you recreate this locally. It's separated by commit to hopefully isolate the error here. Seems like a combination of

```ruby
[] << "data" if true
```

and
```ruby
{}.values_at(*[]).join(",")
```

where the hash contains string interpolation.

The repo is separated by commit, so when I run `bundle exec brakeman` on [this commit](https://github.com/Chris-Brauns-II/brakeman-bug/commit/f14e627f174e2147b999514c71f3aa4f4f8005f6), brakeman finishes.

However, if I run `bundle exec brakeman` on the [next commit](https://github.com/Chris-Brauns-II/brakeman-bug/commit/ea82bde3e4a59cfbf4c9d41904598cdcc15916b2), it errors out.

**Comment by Capncavedan** [comment]
Thanks, @Chris-Brauns-II and @presidentbeef !
