### ISSUE TITLE
config/routes.rb with .root in it throws an exception

### ISSUE THREAD

**Issue by 23tux** [presidentbeef/brakeman#1640]
### Background

Brakeman version: 5.1.1
Rails version: 5.2.6
Ruby version: 2.7.2

### Issue

When using `.root` somewhere in `config/routes.rb` file, Brakeman fails with an exception:

```
# routes.rb

test.root

MyApp::Application.routes.draw do
  # ...
end
```

The exception is
```
root@ac3503ef5c5b:/usr/src/app# brakeman -z --no-pager --table-width=200
Loading scanner...
Processing application in /usr/src/app
Processing gems...
[Notice] Detected Rails 5 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Detecting file types...
Processing initializers...
Processing libs...ssed
Processing routes...
Parsing config/routes.rb
Traceback (most recent call last):
        19: from /usr/local/bundle/bin/brakeman:23:in `<main>'
        18: from /usr/local/bundle/bin/brakeman:23:in `load'
        17: from /usr/local/bundle/gems/brakeman-5.1.1/bin/brakeman:10:in `<top (required)>'
        16: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:20:in `start'
        15: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:35:in `run'
        14: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:166:in `run_report'
        13: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:125:in `regular_report'
        12: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/commandline.rb:157:in `run_brakeman'
        11: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman.rb:86:in `run'
        10: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman.rb:392:in `scan'
         9: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:57:in `process'
         8: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/scanner.rb:253:in `process_routes'
         7: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/processor.rb:35:in `process_routes'
         6: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/processors/lib/rails3_route_processor.rb:24:in `process_routes'
         5: from /usr/local/bundle/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:72:in `process'
         4: from /usr/local/bundle/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:113:in `in_context'
         3: from /usr/local/bundle/gems/brakeman-5.1.1/lib/ruby_parser/bm_sexp_processor.rb:76:in `block in process'
         2: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/processors/lib/rails3_route_processor.rb:34:in `process_call'
         1: from /usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/processors/lib/rails3_route_processor.rb:81:in `process_root'
/usr/local/bundle/gems/brakeman-5.1.1/lib/brakeman/util.rb:142:in `hash_access': undefined method `find_index' for nil:NilClass (NoMethodError)
```

When I do something like

```
# routes.rb

test.my_root
```

it does not trigger in an exception.

**Comment by presidentbeef** [comment]
:facepalm: this is an easy one, sorry it's taken a while to get to.
