### ISSUE TITLE
Brakeman 5.1.x does not run on Ruby 2.4 version

### ISSUE THREAD

**Issue by tjku** [presidentbeef/brakeman#1649]
### Background

Brakeman version: 5.1.2
Ruby version: 2.4.10

### Issue

Version 5.1.0 starts to use `parallel` gem (commit https://github.com/presidentbeef/brakeman/commit/af7ba739a6d34b001e7bdc04d2e388639e2d3bac/) and this gem requires use of Ruby version 2.5. This creates an error when we try to run Brakeman on Ruby version 2.4.

#### Other Error

Run Brakeman with `--debug` to see the full stack trace.

Stack trace:

```
Loading scanner...
/Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:226: syntax error, unexpected keyword_ensure, expecting keyword_end (SyntaxError)
      ensure
            ^
/Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:532: syntax error, unexpected keyword_end, expecting end-of-input
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/file_parser.rb:1:in `<top (required)>'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/scanner.rb:8:in `<top (required)>'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman.rb:378:in `scan'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman.rb:86:in `run'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/commandline.rb:157:in `run_brakeman'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/commandline.rb:125:in `regular_report'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/commandline.rb:166:in `run_report'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/commandline.rb:35:in `run'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/lib/brakeman/commandline.rb:20:in `start'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/lib/ruby/gems/2.4.0/gems/brakeman-5.1.2/bin/brakeman:10:in `<top (required)>'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/bin/brakeman:23:in `load'
	from /Users/tomaszjankuc/.rbenv/versions/2.4.10/bin/brakeman:23:in `<main>'
```

This error does not occur when I run Brakeman version 5.0.4 or if I switch to Ruby 2.5.

**Comment by presidentbeef** [comment]
Thank you for reporting!

I do not plan to make any changes to work with Ruby 2.4, which has been officially unsupported since March 2020. I'll bump the required Ruby version to 2.5.

If you want to use Brakeman with 2.4, you could use the `brakeman-lib` gem and then set a dependency on `parallel` version `1.20.1`.

**Comment by presidentbeef** [comment]
Brakeman 5.2.0 raises the required Ruby version to 2.5.0.
