### ISSUE TITLE
Brakeman failing on GitHub Actions (Invalid request: No more than 50 items are allowed)

### ISSUE THREAD

**Issue by altjx** [presidentbeef/brakeman#1665]
### Background

Brakeman version: 5.2.0
Rails version: 6.1.4.4
Ruby Version: 3.0.2

### Issue

While running brakeman in a GitHub actions workflow, it's failing with the following error:

```
 - CheckTranslateBug
 - CheckUnsafeReflection
 - CheckUnsafeReflectionMethods
 - CheckValidationRegex
 - CheckVerbConfusion
 - CheckWithoutProtection
 - CheckXMLDoS
 - CheckYAMLParsing
Checks finished, collecting results...
Generating report...
/action/lib/github_client.rb:36:in `request_http': Unprocessable Entity: {"message":"Invalid request.\n\nNo more than 50 items are allowed; 63 were supplied.","documentation_url":"https://docs.github.com/rest/reference/checks#update-a-check-run"} (RuntimeError)
	from /action/lib/github_client.rb:10:in `patch'
	from /action/lib/github_check_run_service.rb:22:in `run'
	from /action/lib/index.rb:29:in `<main>'
```

I'm actually not quite sure what this means, lol. I saw a mention of a GitHub actions workflow in #1580 and decided to try it since the one made for GitHub actions is an archived, read-only repository now.

Here's what my GitHub actions workflow looks like:

```
      - name: Brakeman Static Analysis Check
        run: brakeman --format github --no-pager
```

This seems to work fine in the actual docker container, but something about the GH actions process doesn't like the report generation component.

Anyway that I can get around this so I can integrate this into my CI/CD pipeline?

**Comment by altjx** [comment]
Closing. I actually was editing the wrong file. Using the command mentioned in the PR works perfectly.
