### ISSUE TITLE
Parse error when using Ruby 3.1 anonymous block forwarding

### ISSUE THREAD

**Issue by cselmer** [presidentbeef/brakeman#1688]
### Background

Brakeman version: 5.2.1
Rails version: 7.0.2.2
Ruby version: 3.1.1

Link to Rails application code: This code causes Brakeman to throw a parse error.
```
  def self.present_collection(models, &)
    models.map { |model| call(model, &) }
  end
```

### Issue

When using Ruby 3.1 anonymous block forwarding as suggested by the [style guide](https://rubystyle.guide/#block-forwarding), a parse error is thrown:
```
Error: app/presenters/application_presenter.rb:52 :: parse error on value ")" (tRPAREN) Could not parse app/presenters/application_presenter.rb
Location: /Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/racc/parser.rb:538:in `on_error'
```

#### Other Error

Relevant part of the stack trace:

```
app/presenters/application_presenter.rb:52 :: parse error on value ")" (tRPAREN)
Could not parse app/presenters/application_presenter.rb
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/racc/parser.rb:538:in `on_error'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/ruby_parser-3.18.1/lib/ruby_parser_extras.rb:1476:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/ruby_parser-3.18.1/lib/ruby_parser_extras.rb:1500:in `block in process'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:107:in `block in timeout'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:36:in `block in catch'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:36:in `catch'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:36:in `catch'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/3.1.0/timeout.rb:123:in `timeout'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/ruby_parser-3.18.1/lib/ruby_parser_extras.rb:1491:in `process'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/ruby_parser-3.18.1/lib/ruby_parser.rb:36:in `block in process'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/ruby_parser-3.18.1/lib/ruby_parser.rb:33:in `each'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/ruby_parser-3.18.1/lib/ruby_parser.rb:33:in `process'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/file_parser.rb:78:in `parse_ruby'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/file_parser.rb:41:in `block in parse_files'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:515:in `call_with_index'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:485:in `process_incoming_jobs'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:465:in `block in worker'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `fork'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:456:in `worker'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:447:in `block in create_workers'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `each_with_index'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:446:in `create_workers'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:386:in `work_in_processes'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bundle/ruby/2.7.0/gems/parallel-1.21.0/lib/parallel.rb:289:in `map'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/file_parser.rb:36:in `parse_files'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/scanner.rb:76:in `parse_files'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/scanner.rb:49:in `process'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman.rb:392:in `scan'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman.rb:86:in `run'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/commandline.rb:157:in `run_brakeman'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/commandline.rb:125:in `regular_report'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/commandline.rb:166:in `run_report'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/commandline.rb:35:in `run'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/lib/brakeman/commandline.rb:20:in `start'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/brakeman-5.2.1/bin/brakeman:10:in `<top (required)>'
/Users/chris/.asdf/installs/ruby/3.1.1/bin/brakeman:25:in `load'
/Users/chris/.asdf/installs/ruby/3.1.1/bin/brakeman:25:in `<top (required)>'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `load'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli/exec.rb:23:in `run'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:484:in `exec'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/chris/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
/Users/chris/.asdf/installs/ruby/3.1.1/bin/bundle:25:in `load'
/Users/chris/.asdf/installs/ruby/3.1.1/bin/bundle:25:in `<main>'
```

**Comment by cselmer** [comment]
Apologies, I see this is already being tracked here along with other Ruby 3.1 issues. https://github.com/presidentbeef/brakeman/issues/1664
