### ISSUE TITLE
Parse error on Ruby 3.2 anonymous keyword spread

### ISSUE THREAD

**Issue by Mange** [presidentbeef/brakeman#1765]
### Background

Brakeman version: 5.4.1
Rails version: 7.0.4
Ruby version: 3.2.1

Link to Rails application code: N/A

### Issue

Running Brakeman on a Rails app that uses [Ruby 3.2 anonymous keyword argument passing](https://rubyreferences.github.io/rubychanges/3.2.html#anonymous-arguments-passing-improvements) fails with a parse error.

<details>
<summary><strong>Stack trace</strong></summary>

```
Error: app/models/example.rb:3 :: parse error on value ")" (tRPAREN) Could not parse app/models/example.rb
Location: /home/mange/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/racc/parser.rb:538:in `on_error'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/ruby_parser-3.19.2/lib/ruby_parser_extras.rb:1530:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/ruby_parser-3.19.2/lib/ruby_parser_extras.rb:1554:in `block in process'
/home/mange/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/timeout.rb:189:in `block in timeout'
/home/mange/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/timeout.rb:36:in `block in catch'
/home/mange/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/timeout.rb:36:in `catch'
/home/mange/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/timeout.rb:36:in `catch'
/home/mange/.rvm/rubies/ruby-3.2.1/lib/ruby/3.2.0/timeout.rb:198:in `timeout'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/ruby_parser-3.19.2/lib/ruby_parser_extras.rb:1545:in `process'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/ruby_parser-3.19.2/lib/ruby_parser.rb:36:in `block in process'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/ruby_parser-3.19.2/lib/ruby_parser.rb:33:in `each'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/ruby_parser-3.19.2/lib/ruby_parser.rb:33:in `process'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/file_parser.rb:78:in `parse_ruby'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/file_parser.rb:41:in `block in parse_files'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:587:in `call_with_index'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:557:in `process_incoming_jobs'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:537:in `block in worker'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `fork'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:528:in `worker'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:519:in `block in create_workers'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `each_with_index'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:518:in `create_workers'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:457:in `work_in_processes'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bundle/ruby/3.1.0/gems/parallel-1.22.1/lib/parallel.rb:294:in `map'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/file_parser.rb:36:in `parse_files'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/scanner.rb:76:in `parse_files'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/scanner.rb:49:in `process'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman.rb:392:in `scan'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman.rb:86:in `run'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/commandline.rb:157:in `run_brakeman'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/commandline.rb:125:in `regular_report'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/commandline.rb:166:in `run_report'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/commandline.rb:35:in `run'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/lib/brakeman/commandline.rb:20:in `start'
/home/mange/.rvm/gems/ruby-3.2.1/gems/brakeman-5.4.1/bin/brakeman:10:in `<top (required)>'
/home/mange/.rvm/gems/ruby-3.2.1/bin/brakeman:25:in `load'
/home/mange/.rvm/gems/ruby-3.2.1/bin/brakeman:25:in `<main>'
/home/mange/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `eval'
/home/mange/.rvm/gems/ruby-3.2.1/bin/ruby_executable_hooks:22:in `<main>'
```

</details>

## Code to reproduce

```ruby
# app/model/example.rb
class Debug
  def test(**)
    p(**)
  end
end

Debug.new.test(hello: "world")
```

This is valid syntax:
```
> ruby app/models/example.rb
{:hello=>"world"}
```

**Comment by presidentbeef** [comment]
Better to report to [seattlerb/ruby](https://github.com/seattlerb/ruby_parser). I don't see myself having time to submit a PR in the near future.

**Comment by agrobbin** [comment]
I created an issue for this on ruby_parser last night (https://github.com/seattlerb/ruby_parser/issues/338), and they've already fixed it in https://github.com/seattlerb/ruby_parser/commit/81e571fe62fe9a795b9e40a638ebb6b01ab060d3! It should be resolved in the next brakeman release that includes a ruby_parser version update.

**Comment by agrobbin** [comment]
Looks like this fix has been released in ruby_parser [v3.20.2](https://rubygems.org/gems/ruby_parser/versions/3.20.2). @presidentbeef if you have time, it'd be great to get an updated release of brakeman out with this version bump included!

**Comment by ojab** [comment]
https://github.com/presidentbeef/brakeman/pull/1788

**Comment by presidentbeef** [comment]
Brakeman 6.0.1 bundles ruby_parser 3.20.23.
