### ISSUE TITLE
uninitialized constant Brakeman::Report::HTML::URI

### ISSUE THREAD

**Issue by riffraff** [presidentbeef/brakeman#624]
it seems that when running brakeman as

~~~
brakeman -c brakeman/brakeman.conf -i brakeman/brakeman.ignore  --github-repo=user/repo -o brakeman.html
~~~

I consistently receive the error mentioned in the subject, i.e.

~~~
/Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_html.rb:198:in `html_message': uninitialized constant Brakeman::Report::HTML::URI (NameError)
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_html.rb:126:in `with_context'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_html.rb:72:in `convert_warning'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_base.rb:146:in `block in convert_to_rows'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_base.rb:141:in `map'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_base.rb:141:in `convert_to_rows'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_base.rb:128:in `render_warnings'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_base.rb:83:in `generate_warnings'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report/report_html.rb:25:in `generate_report'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report.rb:73:in `generate'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman/report.rb:42:in `format'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:352:in `block (2 levels) in write_report_to_files'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:351:in `open'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:351:in `block in write_report_to_files'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:350:in `each'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:350:in `each_with_index'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:350:in `write_report_to_files'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:339:in `scan'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/lib/brakeman.rb:62:in `run'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/gems/brakeman-3.0.1/bin/brakeman:78:in `<top (required)>'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/bin/brakeman:23:in `load'
	from /Users/riffraff/.rvm/gems/ruby-2.1.5/bin/brakeman:23:in `<main>'
~~~

Running ruby 2.1.5 on OSX:

~~~
$ ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
$ uname -a
Darwin mecbucpro.local 13.4.0 Darwin Kernel Version 13.4.0: Wed Dec 17 19:05:52 PST 2014; root:xnu-2422.115.10~1/RELEASE_X86_64 x86_64
~~~

It seems this happen because URI is used only if using at once

* github url
* html output
* warning file

Adding a `require 'uri'` in `brakeman/report/report_html.rb` fixes the issue, I can provide a pull request but seems silly :)

Thanks for brakeman!

**Comment by presidentbeef** [comment]
Hi Gabriele,

Thanks for reporting this!

Seems to only happen when certain warnings are not present. Must be some other library requires `uri` at some point. Anyhow, the call wasn't really needed and when I looked into it `URI.escape` is deprecated.
