### ISSUE TITLE
Rake task: `SexpTypeError: Result must be a Sexp, was CodeAnalyzer::Nil`

### ISSUE THREAD

**Issue by jstayton** [presidentbeef/brakeman#629]
Hey Justin,

First off, thanks for the library and the work you've put into it!

I've been running Brakeman through a Rake task for a bit now ([as described here](http://brakemanscanner.org/docs/rake/index.html)), and everything has worked fine until a relatively minor change to my app code. I now get this error:

```bash
$ bundle exec rake brakeman:run --trace
** Invoke brakeman:run (first_time)
** Execute brakeman:run
W, [2015-02-27T09:17:56.436684 #12582]  WARN -- : ** [Bugsnag] No API key configured, couldn't notify
rake aborted!
SexpTypeError: Result must be a Sexp, was CodeAnalyzer::Nil:#<CodeAnalyzer::Nil:0x007fadc97e1f70>
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/ruby_parser/bm_sexp_processor.rb:83:in `process'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/processors/lib/find_all_calls.rb:22:in `process_source'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:185:in `block in index_call_sites'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:101:in `block (4 levels) in each_method'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:95:in `each'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:95:in `block (3 levels) in each_method'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:94:in `each'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:94:in `block (2 levels) in each_method'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:93:in `each'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:93:in `block in each_method'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:92:in `each'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:92:in `each_method'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/tracker.rb:184:in `index_call_sites'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/scanner.rb:296:in `index_call_sites'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman/scanner.rb:65:in `process'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman.rb:324:in `scan'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/brakeman-3.0.1/lib/brakeman.rb:62:in `run'
/Users/justinstayton/Monk/Code/monk-id/lib/tasks/brakeman.rake:7:in `block (2 levels) in <top (required)>'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/bugsnag-2.8.1/lib/bugsnag/rake.rb:23:in `block in bugsnag_define_task'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `call'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:240:in `block in execute'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `each'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:235:in `execute'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:172:in `invoke_with_call_chain'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/task.rb:165:in `invoke'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:150:in `invoke_task'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `each'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:106:in `block in top_level'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:115:in `run_with_threads'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:100:in `top_level'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:78:in `block in run'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:176:in `standard_exception_handling'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:75:in `run'
/Users/justinstayton/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rake-10.4.2/bin/rake:33:in `<top (required)>'
/Users/justinstayton/.rbenv/versions/2.1.2/bin/rake:23:in `load'
/Users/justinstayton/.rbenv/versions/2.1.2/bin/rake:23:in `<main>'
Tasks: TOP => brakeman:run
```

I'm not really sure how to debug. The Bugsnag warning is odd and new — I haven't updated the gem recently and I don't get the warning with any other Rake tasks. Not sure if that's just a red herring.

If I run Brakeman directly from the command line, everything works fine:

```bash
$ bundle exec brakeman
```

Help!

**Comment by presidentbeef** [comment]
Hi Justin,

What else do you have in your Gemfile? `CodeAnalyzer` isn't from Brakeman.

Also, I don't recommend using the Rake task if you don't have to...it loads your entire Rails app which is not needed. Probably one of those dependencies is stepping on some of Brakeman's toes...

**Comment by jstayton** [comment]
Oh, strange! There are a decent amount of gems in my Gemfile, so I'm not entirely sure where `CodeAnalyzer` is from.

Regardless, I've switched to not use it programmatically with Rake.

Thanks for the help!
