### ISSUE TITLE
fuck 11 error

### ISSUE THREAD

**Issue by dankohn** [presidentbeef/brakeman#641]
I'm getting the following error when running brakeman on our Rails project:
```
+Errors+
+---------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------->>
| Error                                                                                 | Location                                                                                                      >>
+---------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------->>
| fuck 11 While processing /Users/dan/Dropbox/Documents/dev/chewy/app/models/network.rb | /Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby21_parser.rb:6482:in `_red>>
+---------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------->>
```
When running with `-d` I see:
```
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
fuck 11
While processing /Users/dan/Dropbox/Documents/dev/chewy/app/models/network.rb
/Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby21_parser.rb:6482:in `_reduce_561'
/Users/dan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/racc/parser.rb:258:in `_racc_do_parse_c'
/Users/dan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/racc/parser.rb:258:in `do_parse'
/Users/dan/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/ruby_parser-3.6.5/lib/ruby_parser_extras.rb:1036:in `block in process'
/Users/dan/.rbenv/versions/2.1.5/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
```
brakeman still completes with a valid exit code, but this is a little impolite. The actual code triggering this error seems to be: https://github.com/seattlerb/ruby_parser/blob/master/lib/ruby21_parser.y#L2175

Any suggestions?

**Comment by presidentbeef** [comment]
Hi Dan,

Sorry for the trouble.

As you noticed, this error is not coming from Brakeman, but from ruby_parser. I would guess it is the same as this issue: https://github.com/seattlerb/ruby_parser/issues/180

You could change the code in that one file to something ruby_parser can parse, or wait for that syntax to be supported.

**Comment by dankohn** [comment]
I commented out methods in the file until discovering that the issue was in the line `lambda do |carrier:, provider:|`. The colons do not belong.

**Comment by presidentbeef** [comment]
For what it's worth, that is valid syntax and the next release of ruby_parser will support it.

**Comment by dankohn** [comment]
Yes, thanks. The ruby_parser was very responsive to my team's bug report. https://github.com/seattlerb/ruby_parser/issues/180
