### ISSUE TITLE
ZeroDivisionError 

### ISSUE THREAD

**Issue by vovanmozg** [presidentbeef/brakeman#729]
Hello, 
i'm only install brakeman gem and run it. And got this error:
```
www@vd2:~/rails_projects/app$ brakeman
Loading scanner...
Processing application in /home/www/rails_projects/app
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...ssed
Processing routes...          
Processing templates...       
Processing data flow in templates...
Processing models...          
/home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:145:in `/': divided by 0 (ZeroDivisionError)
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:145:in `process_call'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:363:in `process_attrasgn'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:575:in `process_if_branch'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:553:in `block (2 levels) in process_if'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/sexp_processor-4.6.0/lib/sexp_processor.rb:416:in `scope'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:106:in `scope'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:541:in `block in process_if'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:540:in `each'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:540:in `each_with_index'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:540:in `process_if'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
	from (eval):3:in `map!'
	from (eval):3:in `map!'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:251:in `block in process_defn'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:261:in `block in meth_env'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/sexp_processor-4.6.0/lib/sexp_processor.rb:416:in `scope'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:258:in `meth_env'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/alias_processor.rb:250:in `process_defn'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/lib/processor_helper.rb:5:in `block in process_all'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp.rb:128:in `block in each_sexp'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp.rb:127:in `each'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/ruby_parser/bm_sexp.rb:127:in `each_sexp'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processors/lib/processor_helper.rb:4:in `process_all'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/processor.rb:57:in `process_model'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:286:in `process_model'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:281:in `block in process_models'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:295:in `block in track_progress'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:292:in `each'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:292:in `track_progress'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:279:in `process_models'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman/scanner.rb:59:in `process'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman.rb:327:in `scan'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/lib/brakeman.rb:62:in `run'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/gems/brakeman-3.1.1/bin/brakeman:78:in `<top (required)>'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/bin/brakeman:23:in `load'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/bin/brakeman:23:in `<main>'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/bin/ruby_executable_hooks:15:in `eval'
	from /home/www/.rvm/gems/ruby-2.2.0@rails420/bin/ruby_executable_hooks:15:in `<main>'
```

Ruby version 2.2.0
Rails 4.2.0

"brakeman -d" says that error occured in one of the models:
```Processing /home/www/rails_projects/app/app/models/enrollment.rb```

I can't post this enrollment.rb code, but i can try debug brakeman gem. Can i run brakeman process from my rails app, so that I can debug this error in my IDE?

**Comment by vovanmozg** [comment]
i solve trouble when change one line in model's code:
from
```self.data[:complete] = self.data[:finished] * 100 / self.data[:all]```
to
```self.data[:complete] = (self.data[:finished] / self.data[:all]) * 100```

**Comment by vovanmozg** [comment]
Thank you
