### ISSUE TITLE
Exception when processing data flow in controllers

### ISSUE THREAD

**Issue by sgringwe** [presidentbeef/brakeman#763]
I am receiving the following error when running 'brakeman'.

``` brakeman
Loading scanner...
Processing application in /Users/stallion/code/project
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...ssed
Processing routes...
Processing templates...
Processing data flow in templates...
Processing models...
Processing controllers...
Processing data flow in controllers...
/Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_processor.rb:239:in `process_iter': Expected call or attrasgn or super or zsuper or result but given s(:hash, s(:or, s(:call, s(:call, s(:lvar, :parent_assoc), :[], s(:lit, :alias)), :+, s(:call, s(:lvar, :table_count), :to_s, s(:lit, 16))), s(:call, s(:lvar, :table_count), :to_s, s(:lit, 16))), s(:array)) (WrongSexpError)
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/base_processor.rb:34:in `block in process_default'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/base_processor.rb:32:in `each'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/base_processor.rb:32:in `each_with_index'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/base_processor.rb:32:in `process_default'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:77:in `block in process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/base_processor.rb:48:in `process_if'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/lib/processor_helper.rb:13:in `block in process_all!'
	from (eval):3:in `map!'
	from (eval):3:in `map!'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/lib/processor_helper.rb:11:in `process_all!'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_processor.rb:194:in `process_defn'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_alias_processor.rb:56:in `block (2 levels) in process_mixins'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_alias_processor.rb:49:in `each'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_alias_processor.rb:49:in `block in process_mixins'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_alias_processor.rb:41:in `each'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_alias_processor.rb:41:in `process_mixins'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_alias_processor.rb:33:in `process_controller'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processor.rb:51:in `process_controller_alias'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:234:in `block (2 levels) in process_controller_data_flows'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:233:in `each'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:233:in `block in process_controller_data_flows'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:295:in `block in track_progress'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:292:in `each'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:292:in `track_progress'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:231:in `process_controller_data_flows'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/scanner.rb:63:in `process'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman.rb:331:in `scan'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman.rb:62:in `run'
	from /Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/bin/brakeman:78:in `<top (required)>'
	from /Users/stallion/.rbenv/versions/2.2.2/bin/brakeman:23:in `load'
	from /Users/stallion/.rbenv/versions/2.2.2/bin/brakeman:23:in `<main>'```

**Comment by presidentbeef** [comment]
Hi Scott,

I could work around this pretty easily, but I'm curious what code led to this problem. If you run Brakeman with `-d` it should indicate roughly where the issue is occurring. Would you be able to share that code or a sanitized version of it?

**Comment by sgringwe** [comment]
@presidentbeef it's somewhat complex code for generating reports for users. The output:

```
rocessing GeneratedReportsController#show
Processing GeneratedReportsController#download
Processing GeneratedReportsController#preview
Processing GeneratedReportsController#create
Processing GeneratedReportsController#generated_report_params
Rendering layouts/application (["GeneratedReportsController#generated_report_params"])
Rendering generated_reports/generated_report_params (["GeneratedReportsController#generated_report_params"])
[Notice] No such template: generated_reports/generated_report_params
Processing GeneratedReportsController#build_join
Rendering layouts/application (["GeneratedReportsController#build_join"])
Rendering generated_reports/build_join (["GeneratedReportsController#build_join"])
[Notice] No such template: generated_reports/build_join
Processing GeneratedReportsController#columns_for_class
Rendering layouts/application (["GeneratedReportsController#columns_for_class"])
Rendering generated_reports/columns_for_class (["GeneratedReportsController#columns_for_class"])
[Notice] No such template: generated_reports/columns_for_class
Processing GeneratedReportsController#csv_from_table
Rendering layouts/application (["GeneratedReportsController#csv_from_table"])
Rendering generated_reports/csv_from_table (["GeneratedReportsController#csv_from_table"])
[Notice] No such template: generated_reports/csv_from_table
Processing GeneratedReportsController#each_child
Rendering layouts/application (["GeneratedReportsController#each_child"])
Rendering generated_reports/each_child (["GeneratedReportsController#each_child"])
[Notice] No such template: generated_reports/each_child
Processing GeneratedReportsController#each_column
Rendering layouts/application (["GeneratedReportsController#each_column"])
Rendering generated_reports/each_column (["GeneratedReportsController#each_column"])
[Notice] No such template: generated_reports/each_column
/Users/stallion/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/brakeman-3.1.2/lib/brakeman/processors/controller_processor.rb:239:in `process_iter': Expected call or attrasgn or super or zsuper or result but given s(:hash, s(:or, s(:call, s(:call, s(:lvar, :parent_assoc), :[], s(:lit, :alias)), :+, s(:call, s(:lvar, :table_count), :to_s, s(:lit, 16))), s(:call, s(:lvar, :table_count), :to_s, s(:lit, 16))), s(:array)) (WrongSexpError)
```

The each_column method:
```
def each_column(report_hierarchy)
    data = each_child(report_hierarchy) do |_parent, child|
      child["columns"].each do |column|
        yield(column)
      end
    end
    data
  end
```
does that help?

**Comment by presidentbeef** [comment]
Doesn't make sense yet. Where do the `parent_assoc[:alias]` and `table_count.to_s(16)` keys come from?

If you can provide an example that reproduces the problem, that would be amazing.
