### ISSUE TITLE
Regression in v3.1.0: brakeman hangs on nested modules in controllers

### ISSUE THREAD

**Issue by ggilder** [presidentbeef/brakeman#785]
Hello, it seems that https://github.com/presidentbeef/brakeman/commit/8229763545bf47556961e1f6eeeb70397e0a5f20 introduced a regression that hangs brakeman on certain input (still trying to produce a reduced test case, but figured I'd submit this info in case this is enough to fix).

On that specific SHA, brakeman actually exits with the following error:
```
Loading scanner...
Processing application in /Users/gabriel/Development/web
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...ssed
Processing routes...
Processing templates...
Processing data flow in templates...
Processing models...
Processing controllers...
Processing data flow in controllers...
/Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_processor.rb:233:in `process_defs': undefined method `node_type' for #<Hash:0x007fc39ecdbf90> (NoMethodError)
    from /Users/gabriel/oss/brakeman/lib/ruby_parser/bm_sexp_processor.rb:80:in `block in process'
    from /Users/gabriel/oss/brakeman/lib/ruby_parser/bm_sexp_processor.rb:149:in `in_context'
    from /Users/gabriel/oss/brakeman/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_alias_processor.rb:58:in `block (2 levels) in process_mixins'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_alias_processor.rb:48:in `each'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_alias_processor.rb:48:in `block in process_mixins'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_alias_processor.rb:40:in `each'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_alias_processor.rb:40:in `process_mixins'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_alias_processor.rb:32:in `process_controller'
    from /Users/gabriel/oss/brakeman/lib/brakeman/processor.rb:51:in `process_controller_alias'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:225:in `block (2 levels) in process_controller_data_flows'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:224:in `each_value'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:224:in `block in process_controller_data_flows'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:286:in `block in track_progress'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:283:in `each'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:283:in `track_progress'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:222:in `process_controller_data_flows'
    from /Users/gabriel/oss/brakeman/lib/brakeman/scanner.rb:63:in `process'
    from /Users/gabriel/oss/brakeman/lib/brakeman.rb:324:in `scan'
    from /Users/gabriel/oss/brakeman/lib/brakeman.rb:62:in `run'
    from bin/brakeman:78:in `<main>'
```

In the actual release of 3.1.0, I see just the first line of the error, i.e.

```
/Users/gabriel/oss/brakeman/lib/brakeman/processors/controller_processor.rb:233:in `process_defs'
```

and then the process appears to hang.

Any ideas? In the meantime I'll try to reduce a test case.

**Comment by presidentbeef** [comment]
Hi Gabriel, sorry for the trouble.

I'm guessing there's a `def <something>.something` where `<something>` is not `self`?

Also if you run with `-d` it should help narrow the search.

**Comment by ggilder** [comment]
I was able to produce a test case. https://github.com/ggilder/brakeman_test works with brakeman 3.0.5, errors on 3.1.0. https://github.com/ggilder/brakeman_test/commit/384ca5b7388c5dc7f81654fb2e3b8bfa1c1515e8 is the specific code that triggers it. Hope that helps!

**Comment by presidentbeef** [comment]
Yes, it seems there's a mixup of how the current module is getting tracked (symbols some places, hashes in others). I'll see what I can do about it.

Thanks for letting me know!
