### ISSUE TITLE
Error when processing [path]: Result must be a Sexp, was NilClass:nil (SexpTypeError)

### ISSUE THREAD

**Issue by dblandin** [presidentbeef/brakeman#837]
Hey there,

I'm consistently seeing a parse error for the following haml snippet. HAML seems to load and render it just fine but I can't get brakeman to complete an analysis when the file is included.

```
$ brakeman --version
brakeman 3.2.1
$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin15]
```

Thanks in advance for your help!

## Ruby snippet causing parse error

`app/views/pages/parts_kit.html.haml`

```ruby
= find_and_preserve do
  %pre
    :escaped
      <p class="input-container input-container-5">
        <label for="f1">Name</label>
        <input class="input" id="f1" placeholder=".input-container-5" type="text">
      </p>
      <p class="input-container input-container-10">
        <label for="f2">Address</label>
        <input class="input" id="f2" placeholder=".input-container-10" type="text">
      </p>
```

## Brakeman output

```console
$ brakeman --debug
Loading scanner...
Processing application in /Users/devon/brakeman-test
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Parsing /Users/devon/brakeman-test/config/initializers/assets.rb
Parsing /Users/devon/brakeman-test/config/initializers/backtrace_silencers.rb
Parsing /Users/devon/brakeman-test/config/initializers/cookies_serializer.rb
Parsing /Users/devon/brakeman-test/config/initializers/filter_parameter_logging.rb
Parsing /Users/devon/brakeman-test/config/initializers/inflections.rb
Parsing /Users/devon/brakeman-test/config/initializers/mime_types.rb
Parsing /Users/devon/brakeman-test/config/initializers/session_store.rb
Parsing /Users/devon/brakeman-test/config/initializers/wrap_parameters.rb
Parsing /Users/devon/brakeman-test/app/controllers/application_controller.rb
Parsing /Users/devon/brakeman-test/app/controllers/parts_controller.rb
Parsing /Users/devon/brakeman-test/app/views/layouts/application.html.erb
Parsing /Users/devon/brakeman-test/app/views/layouts/application.html.erb
Parsing /Users/devon/brakeman-test/app/views/pages/parts_kit.html.haml
Parsing /Users/devon/brakeman-test/app/views/pages/parts_kit.html.haml
Processing initializers...
Processing /Users/devon/brakeman-test/config/initializers/assets.rb
Processing /Users/devon/brakeman-test/config/initializers/cookies_serializer.rb
Processing /Users/devon/brakeman-test/config/initializers/filter_parameter_logging.rb
Processing /Users/devon/brakeman-test/config/initializers/session_store.rb
Processing /Users/devon/brakeman-test/config/initializers/wrap_parameters.rb
Processing libs...
Processing routes...
Processing templates...
Processing /Users/devon/brakeman-test/app/views/layouts/application.html.erb
Processing /Users/devon/brakeman-test/app/views/pages/parts_kit.html.haml
/usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:81:in `process': Error when processing pages/parts_kit: Error when processing pages/parts_kit: Error when processing pages/parts_kit: Error when processing pages/parts_kit: Result must be a Sexp, was NilClass:nil (SexpTypeError)
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/template_processor.rb:24:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/base_processor.rb:57:in `process_iter'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/template_processor.rb:24:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/template_processor.rb:39:in `process_lasgn'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/template_processor.rb:24:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/haml_template_processor.rb:119:in `block in process_block'
        from (eval):3:in `map!'
        from (eval):3:in `map!'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/haml_template_processor.rb:118:in `process_block'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:75:in `block in process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:112:in `in_context'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/ruby_parser/bm_sexp_processor.rb:71:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processors/template_processor.rb:24:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/processor.rb:66:in `process_template'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:268:in `process_template'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:263:in `block in process_templates'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:300:in `block in track_progress'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:297:in `each'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:297:in `track_progress'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:261:in `process_templates'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman/scanner.rb:55:in `process'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman.rb:336:in `scan'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/lib/brakeman.rb:61:in `run'
        from /usr/local/opt/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/brakeman-3.2.1/bin/brakeman:79:in `<top (required)>'
        from /usr/local/opt/rbenv/versions/2.2.0/bin/brakeman:23:in `load'
        from /usr/local/opt/rbenv/versions/2.2.0/bin/brakeman:23:in `<main>'
```

## HAML Syntax Check

```console
$ haml -e --debug app/views/pages/parts_kit.html.haml
haml_temp =  find_and_preserve do
_hamlout.push_text("<pre>&lt;p class=&quot;input-container input-container-5&quot;&gt;\n  &lt;label for=&quot;f1&quot;&gt;Name&lt;/label&gt;\n  &lt;input class=&quot;input&quot; id=&quot;f1&quot; placeholder=&quot;.input-container-5&quot; type=&quot;text&quot;&gt;\n&lt;/p&gt;\n&lt;p class=&quot;input-container input-container-10&quot;&gt;\n  &lt;label for=&quot;f2&quot;&gt;Address&lt;/label&gt;\n  &lt;input class=&quot;input&quot; id=&quot;f2&quot; placeholder=&quot;.input-container-10&quot; type=&quot;text&quot;&gt;\n&lt;/p&gt;</pre>\n", 0, false);end;_hamlout.buffer << _hamlout.format_script_false_false_false_true_false_false_false(haml_temp);_hamlout.push_text("\n", 0, false);
====================================================================================================
&lt;pre&gt;&amp;lt;p class=&amp;quot;input-container input-container-5&amp;quot;&amp;gt;&amp;#x000A;  &amp;lt;label for=&amp;quot;f1&amp;quot;&amp;gt;Name&amp;lt;/label&amp;gt;&amp;#x000A;  &amp;lt;input class=&amp;quot;input&amp;quot; id=&amp;quot;f1&amp;quot; placeholder=&amp;quot;.input-container-5&amp;quot; type=&amp;quot;text&amp;quot;&amp;gt;&amp;#x000A;&amp;lt;/p&amp;gt;&amp;#x000A;&amp;lt;p class=&amp;quot;input-container input-container-10&amp;quot;&amp;gt;&amp;#x000A;  &amp;lt;label for=&amp;quot;f2&amp;quot;&amp;gt;Address&amp;lt;/label&amp;gt;&amp;#x000A;  &amp;lt;input class=&amp;quot;input&amp;quot; id=&amp;quot;f2&amp;quot; placeholder=&amp;quot;.input-container-10&amp;quot; type=&amp;quot;text&amp;quot;&amp;gt;&amp;#x000A;&amp;lt;/p&amp;gt;&lt;/pre&gt;
```

**Comment by presidentbeef** [comment]
Hi Devon,

Thank you for the detailed report! I think I know what the issue is. Should be able to resolve shortly.

**Comment by dblandin** [comment]
Thanks @presidentbeef!
