### ISSUE TITLE
Crash on undefined method "terminal_size"

### ISSUE THREAD

**Issue by jvoisin** [presidentbeef/brakeman#865]
I just installed brakeman with `gem install brakeman`, and ran it on a codebase, then got this stacktrace:

```
jvoisin@mim 15:12  ./dnca_src 
Loading scanner...
Processing application in /home/jvoisin/---/---/---
Processing gems...
[Notice] Detected Rails 4 application
Processing configuration...
[Notice] Escaping HTML by default
Parsing files...
Processing initializers...
Processing libs...ssed
Processing routes...          
Processing templates...       
Processing data flow in templates...
Processing models...          
Processing controllers...     
Processing data flow in controllers...
Indexing call sites...        
Running checks in parallel...
 - CheckBasicAuth
 - CheckBasicAuthTimingAttack
 - CheckCrossSiteScripting
 - CheckContentTag
 - CheckCreateWith
 - CheckDefaultRoutes
 - CheckDeserialize
 - CheckDetailedExceptions
 - CheckDigestDoS
 - CheckDynamicFinders
 - CheckEscapeFunction
 - CheckEvaluation
 - CheckExecute
 - CheckFileAccess
 - CheckFileDisclosure
 - CheckFilterSkipping
 - CheckForgerySetting
 - CheckHeaderDoS
 - CheckI18nXSS
 - CheckJRubyXML
 - CheckJSONEncoding
 - CheckJSONParsing
 - CheckLinkTo
 - CheckLinkToHref
 - CheckMailTo
 - CheckMassAssignment
 - CheckMimeTypeDoS
 - CheckModelAttrAccessible
 - CheckModelAttributes
 - CheckModelSerialize
 - CheckNestedAttributes
 - CheckNestedAttributesBypass
 - CheckNumberToCurrency
 - CheckQuoteTableName
 - CheckRedirect
 - CheckRegexDoS
 - CheckRender
 - CheckRenderDoS
 - CheckRenderInline
 - CheckResponseSplitting
 - CheckRouteDoS
 - CheckSafeBufferManipulation
 - CheckSanitizeMethods
 - CheckSelectTag
 - CheckSelectVulnerability
 - CheckSend
 - CheckSendFile
 - CheckSessionManipulation
 - CheckSessionSettings
 - CheckSimpleFormat
 - CheckSingleQuotes
 - CheckSkipBeforeFilter
 - CheckSQL
 - CheckSQLCVEs
 - CheckSSLVerify
 - CheckStripTags
 - CheckSymbolDoSCVE
 - CheckTranslateBug
 - CheckUnsafeReflection
 - CheckValidationRegex
 - CheckWithoutProtection
 - CheckXMLDoS
 - CheckYAMLParsing
Checks finished, collecting results...
Generating report...
/var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman/util.rb:446:in `truncate_table': undefined method `terminal_size' for #<HighLine:0x00000009291b08> (NoMethodError)
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman/report/report_table.rb:7:in `generate_report'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman/report.rb:76:in `generate'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman/report.rb:67:in `to_s'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman/report.rb:38:in `format'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman.rb:373:in `block in write_report_to_formats'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman.rb:372:in `each'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman.rb:372:in `write_report_to_formats'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman.rb:355:in `scan'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/lib/brakeman.rb:61:in `run'
	from /var/lib/gems/2.1.0/gems/brakeman-3.2.1/bin/brakeman:79:in `<top (required)>'
	from /usr/local/bin/brakeman:23:in `load'
	from /usr/local/bin/brakeman:23:in `<main>'
zsh: exit 1     brakeman ./---
```

**Comment by presidentbeef** [comment]
Hello,

Please see #842 and #767. You have a very old version of RubyGems (the `gem` command) from 2013. It has a bug where it will install the pre-release of a gem (in this case `highline`) when it shouldn't. This was fixed in RubyGems v2.3.0 in 2014. You can try updating with `gem update --system`.

Or you can uninstall `highline` and install the correct version:

    gem uninstall highline
    gem install highline -v 1.7.8
